package net.constant;

public class VisitorManagementConstants {
	
	public static String ADD_PERSON_STORED_PROC="CREATE_NEW_PERSON_PKG.ADD_PERSON";
	
	public static String ADD_FINGERPRINT_STORED_PROC="CREATE_NEW_PERSON_PKG.ADD_FINGERPRINT";

	public static String GET_PERSON_DETAILS_STORED_PROC="GET_PERSON_DETAILS_PKG.GET_PERSON";
	
	public static String GET_PERSON_IMAGE_PROC_NAME="GET_PERSON_DETAILS_PKG.GET_PERSON_PHOTO";
	
	public static String GET_PERSON_FINGERPRINT_PROC_NAME="GET_PERSON_DETAILS_PKG.GET_PERSON_FINGERPRINT";

	public static String FIND_PERSON_PROC_NAME="GET_PERSON_DETAILS_PKG.FIND_PERSON";
	
	public static String GET_DROPDOWN_VALUES_PROC_NAME="DROPDOWN_SERVICE_PKG.GET_DROPDOWN";
	
	public static String AUTHENTICATE_USER_PROC_NAME="AUTHENTICATE_USER_PKG.AUTHENTICATE_USER";
	

	public static String PERSON_OBJECT="PERSON_DETAILS_RECORD";
	
	public static String DROPDOWN_OBJECT="DROPDOWN_RECORD";
	
	public static String DROPDOWN_LIST="DROPDOWN_LIST";
	
	
	

}
